name: core_datasources
description: Shared datasources for Dash apps
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  # Allow apps to choose their FlutterFire major (4.x or 5.x).
  cloud_firestore: ">=4.15.5 <6.0.0"
  # Allow apps to choose their FlutterFire major (4.x or 5.x).
  cloud_functions: ">=4.6.5 <6.0.0"
  core_models:
    path: ../core_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

