name: core_datasources
description: Shared datasources for Dash apps
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  cloud_firestore: ^4.15.5
  cloud_functions: ^4.6.5
  core_models:
    path: ../core_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

