name: dash_web
description: Operon Client Web.
publish_to: none
version: 1.1.0+2
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^14.0.2
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  cloud_functions: ^5.0.0
  firebase_storage: ^12.0.1
  firebase_database: ^11.0.0
  shared_preferences: ^2.3.2
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  image_picker_for_web: ^3.1.1
  simple_web_camera: ^1.0.11
  qr_flutter: ^4.1.0
  pdf: ^3.11.1
  printing: ^5.13.1
  http: ^1.2.0
  flutter_staggered_animations: ^1.1.1
  google_maps_flutter: ^2.14.0
  google_fonts: ^6.1.0
  google_polyline_algorithm: ^3.1.0
  intl: ^0.19.0
  excel: ^4.0.2
  share_plus: ^10.0.0
  fl_chart: ^0.68.0
  js: ^0.6.7
  package_info_plus: ^8.0.3
  core_bloc:
    path: ../../packages/core_bloc
  core_models:
    path: ../../packages/core_models
  core_services:
    path: ../../packages/core_services
  core_ui:
    path: ../../packages/core_ui
  core_utils:
    path: ../../packages/core_utils
  core_datasources:
    path: ../../packages/core_datasources

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/branding/operon_app_icon.png
    - assets/branding/operon_splash_logo.png
    - assets/branding/
