name: dash_web
description: Dash Web app sharing most modules with Dash Mobile.
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^14.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.7.7
  shared_preferences: ^2.3.2
  core_bloc:
    path: ../../packages/core_bloc
  core_models:
    path: ../../packages/core_models
  core_services:
    path: ../../packages/core_services
  core_ui:
    path: ../../packages/core_ui
  core_utils:
    path: ../../packages/core_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
