name: core_ui
description: Dash design system widgets, themes, and layout primitives.
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  core_models:
    path: ../core_models
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
